import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WorkspaceShell search integration', () => {
  it('mounts the global search dialog and exposes a shared top-bar trigger with keyboard shortcut handling', () => {
    const source = readFileSync(resolve('src/views/WorkspaceShell.vue'), 'utf8')
    const dialogSource = readFileSync(resolve('src/components/GlobalSearchDialog.vue'), 'utf8')

    expect(source).toContain('data-testid="workspace-shell"')
    expect(source).toContain('data-testid="open-global-search"')
    expect(source).toContain('data-testid="open-notifications-panel"')
    expect(source).toContain('<UserAccountMenu @logout="doLogout" />')
    expect(source).toContain('<GlobalSearchDialog />')
    expect(source).toContain("window.addEventListener('keydown', this.onGlobalKeydown)")
    expect(source).toContain("(event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k'")
    expect(source).toContain('this.searchStore.openDialog()')
    expect(dialogSource).toContain('@keyup.enter="submitSearch"')
    expect(dialogSource).toContain('data-testid="global-search-validation"')
    expect(dialogSource).toContain('<n-date-picker')
    expect(dialogSource).toContain('search-dialog-card')
    expect(dialogSource).toContain('@update:value="onDateFilterChange(\'after\', $event)"')
    expect(dialogSource).toContain('data-testid="global-search-tab-meetings"')
    expect(dialogSource).toContain("searchStore.activeTab === 'meetings'")
    expect(dialogSource).toContain("return this.$t('search.placeholders.meetings')")
    expect(dialogSource).toContain("return this.searchStore.hasSearched")
    expect(dialogSource).toContain("this.$t('search.filters.author_speaker')")
    expect(dialogSource).toContain('data-testid="search-meetings-author-speaker-note"')
    expect(dialogSource).toContain("search.notices.meetings_author_speaker_summary_hidden")
    expect(dialogSource).toContain("if (result?.document_type === 'meeting_summary')")
    expect(dialogSource).toContain("if (result?.document_type === 'meeting_transcript_segment')")
    expect(dialogSource).toContain("if (result?.document_type === 'meeting_transcript')")
    expect(dialogSource).toContain("result?.document_type === 'message'")
    expect(dialogSource).toContain("result?.document_type === 'meeting_transcript_segment'")
    expect(dialogSource).toContain("this.$t('search.result_kinds.chat')")
    expect(dialogSource).toContain('search-result-kind')
    expect(dialogSource).toContain('resultTitle(result)')
    expect(dialogSource).toContain("if (result?.document_type === 'message')")
    expect(dialogSource).toContain("|| result?.document_type === 'meeting_transcript_segment'")
    expect(dialogSource).toContain('return result?.title || result?.snippet || this.fallbackResultTitle(result)')
    expect(dialogSource).not.toContain('search-dialog-title')
    expect(dialogSource).not.toContain('preset="card"')
    expect(dialogSource).not.toContain('scheduleSearch')
  })
})
