import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('MeetingView', () => {
  it('does not render the ended-meeting group chat CTA anymore', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).not.toContain('ui.views.create_group_chat')
    expect(source).not.toContain('canCreateGroupFromMeeting')
    expect(source).not.toContain('createGroupFromMeeting')
  })

  it('uses a focus layout with overlay chat while screen share is maximized', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')
    const overlaySource = readFileSync(resolve('src/components/ScreenShareChatOverlay.vue'), 'utf8')

    expect(source).toContain("v-if=\"meeting && !shareMaximized\"")
    expect(source).toContain('v-if="shouldShowMeetingContentArea"')
    expect(source).toContain(":class=\"{ 'ended-meeting-layout': isEndedMeetingView }\"")
    expect(source).toContain('<ScreenShareChatOverlay')
    expect(source).toContain('test-id-prefix="meeting"')
    expect(source).toContain(':active="canShowShareChatOverlay"')
    expect(overlaySource).toContain("testId('screen-share-chat-overlay')")
    expect(overlaySource).toContain("testId('show-screen-share-chat-peek')")
    expect(source).not.toContain("content-area.compressed")
    expect(overlaySource).toContain("height: min(50vh, 420px);")
  })

  it('uses an adaptive live stage for video-focused and share-focused meeting layouts', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain('data-testid="meeting-live-stage"')
    expect(source).toContain(':class="meetingStageMode"')
    expect(source).toContain('v-if="isShareFocused"')
    expect(source).toContain('data-testid="meeting-share-stage"')
    expect(source).toContain(":variant=\"isMobileLayout ? 'focus' : 'strip'\"")
    expect(source).toContain(":variant=\"isMobileLayout ? 'focus' : 'grid'\"")
    expect(source).toContain('meetingStageMode()')
    expect(source).toContain("return this.isShareFocused ? 'share-focused' : 'video-focused'")
    expect(source).toContain('shouldShowLiveMeetingStage()')
    expect(source).toContain('shouldShowMeetingContentArea()')
    expect(source).toContain('!this.shareMaximized && !this.isShareFocused')
    expect(source).toContain('meeting-live-stage.share-focused')
    expect(source).toContain('.share-panel-wrap.stage :deep(.screen-share-video)')
  })

  it('uses generic ui store screen share state while preserving meeting behavior', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')
    const controlsSource = readFileSync(resolve('src/components/ScreenShareControls.vue'), 'utf8')

    expect(source).toContain("return this.uiStore.screenSharePanelVisible || (this.hasActiveShare && !this.uiStore.hideScreenSharePanel)")
    expect(controlsSource).toContain('this.uiStore.openScreenSharePanel()')
    expect(source).toContain('this.uiStore.closeScreenSharePanel()')
    expect(source).toContain('this.uiStore.setScreenShareMaximized(!this.shareMaximized)')
    expect(source).toContain('this.uiStore.setScreenShareChatVisible(!this.shareChatOpen, {')
    expect(source).toContain('requireMaximized: this.shareMaximized')
  })

  it('animates the share trigger dot only while an active share is hidden', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')
    const controlsSource = readFileSync(resolve('src/components/ScreenShareControls.vue'), 'utf8')

    expect(source).toContain(':share-hidden="isShareHidden"')
    expect(source).toContain("isShareHidden()")
    expect(controlsSource).toContain(":class=\"{ 'share-hidden-indicator': shareHidden }\"")
    expect(controlsSource).toContain(".share-hidden-indicator :deep(.n-badge-sup)")
    expect(controlsSource).toContain("@keyframes share-hidden-pulse")
    expect(controlsSource).not.toContain("transform: scale(1.18);")
  })

  it('offers a publish-quality selector before starting a screen share', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')
    const controlsSource = readFileSync(resolve('src/components/ScreenShareControls.vue'), 'utf8')

    expect(source).toContain('<ScreenShareControls')
    expect(source).toContain('test-id-prefix="meeting"')
    expect(controlsSource).toContain("testId('screen-share-quality-select')")
    expect(controlsSource).toContain('screen_share_sender_quality')
    expect(controlsSource).toContain('sharePublishQualityOptions()')
    expect(controlsSource).toContain('qualityProfile: this.voiceStore.screenSharePublishQuality')
  })

  it('renders meeting video only for an active connected meeting call', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')
    const gridSource = readFileSync(resolve('src/components/MeetingVideoGrid.vue'), 'utf8')

    expect(source).toContain("const MeetingVideoGrid = defineAsyncComponent(() => import('../components/MeetingVideoGrid.vue'))")
    expect(source).toContain('<MeetingVideoGrid')
    expect(source).toContain('resolvedMeetingFocusParticipantId')
    expect(source).toContain(':focused-participant-id="resolvedMeetingFocusParticipantId"')
    expect(source).toContain(':allow-hide-videos="true"')
    expect(source).toContain('shouldShowVideoGrid()')
    expect(source).toContain('shouldShowCollapsedMeetingVideoBar()')
    expect(source).toContain(':show-video-restore="shouldShowCollapsedMeetingVideoBar"')
    expect(source).toContain('@show-videos="showMeetingVideos"')
    expect(source).not.toContain('data-testid="meeting-video-collapsed-bar"')
    expect(source).toContain("this.meeting.status === 'active'")
    expect(source).toContain('this.voiceStore.channelId === this.meeting.chat_channel_id')
    expect(source).toContain('this.voiceStore.meetingVideoEnabled')
    expect(source).toContain('meetingVideosVisible')
    expect(source).toContain('hideMeetingVideos()')
    expect(source).toContain('showMeetingVideos()')
    expect(gridSource).toContain('data-testid="meeting-video-grid"')
    expect(gridSource).toContain('data-testid="meeting-video-toggle-camera"')
    expect(gridSource).toContain('this.voiceStore.toggleCamera()')
  })

  it('moves mobile meeting actions and video management into compact overflow surfaces', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain('data-testid="meeting-mobile-overflow-trigger"')
    expect(source).toContain('data-testid="meeting-mobile-overflow-menu"')
    expect(source).toContain('meeting-header-compact-menu')
    expect(source).toContain('meeting-ended-menu-action')
    expect(source).toContain('data-testid="meeting-mobile-overflow-members"')
    expect(source).toContain('data-testid="meeting-mobile-overflow-edit-title"')
    expect(source).toContain('data-testid="meeting-mobile-overflow-language"')
    expect(source).toContain('data-testid="meeting-mobile-overflow-source"')
    expect(source).toContain("isCompactEndedMeetingMobileLayout")
    expect(source).toContain("data-testid=\"meeting-ended-mobile-header\"")
    expect(source).toContain("data-testid=\"meeting-ended-mobile-meta\"")
    expect(source).toContain('data-testid="meeting-mobile-video-controls"')
    expect(source).toContain('showMobileActionMenu')
    expect(source).toContain('showMeetingVideoPanel')
    expect(source).toContain('data-testid="meeting-video-mobile-drawer"')
    expect(source).toContain('data-testid="meeting-video-mobile-toggle-camera"')
    expect(source).toContain("const VideoSettingsContent = defineAsyncComponent(() => import('../components/VideoSettingsContent.vue'))")
    expect(source).toContain('<VideoSettingsContent :active="showMeetingVideoPanel && isMobileLayout" />')
    expect(source).not.toContain('data-testid="meeting-video-mobile-background-blur"')
    expect(source).toContain("openMeetingVideoPanel()")
    expect(source).toContain("closeMeetingVideoPanel()")
    expect(source).toContain('toggleMeetingVideoCamera()')
    expect(source).not.toContain('setMeetingBackgroundBlur(enabled)')
    expect(source).toContain('meetingVideoParticipantControls()')
    expect(source).toContain("this.voiceStore.setAllRemoteCameraSubscriptions(!this.allIncomingMeetingVideosEnabled)")
    expect(source).toContain('toggleMeetingParticipantIncomingVideo(participantId)')
  })

  it('delegates artifact rendering to focused components while preserving tabs and events', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain("const MeetingSummaryPanel = defineAsyncComponent(() => import('../components/MeetingSummaryPanel.vue'))")
    expect(source).toContain("const MeetingTranscriptPanel = defineAsyncComponent(() => import('../components/MeetingTranscriptPanel.vue'))")
    expect(source).toContain("const AskMeetingPanel = defineAsyncComponent(() => import('../components/AskMeetingPanel.vue'))")
    expect(source).toContain("const TranscriptionRecordingBanner = defineAsyncComponent(() => import('../components/TranscriptionRecordingBanner.vue'))")
    expect(source).toContain('meeting-artifact-hub')
    expect(source).toContain('data-testid="meeting-ended-compact-strip"')
    expect(source).toContain('data-testid="meeting-ended-compact-active-tab"')
    expect(source).toContain('data-testid="meeting-ended-actions-trigger"')
    expect(source).toContain('data-testid="meeting-ended-actions-sheet"')
    expect(source).toContain('data-testid="meeting-ended-actions-menu"')
    expect(source).toContain('data-testid="meeting-ended-action-summary"')
    expect(source).toContain('data-testid="meeting-ended-action-transcript"')
    expect(source).toContain('data-testid="meeting-ended-action-ask"')
    expect(source).toContain('data-testid="meeting-ended-action-chat"')
    expect(source).toContain("openEndedMeetingCompactMenuAction(action)")
    expect(source).toContain("this.setEndedMeetingArtifactTab(action)")
    expect(source).toContain("if (action === 'chat') {")
    expect(source).not.toContain('data-testid="meeting-open-ended-chat"')
    expect(source).toContain('endedMeetingArtifactTabs')
    expect(source).toContain('activeEndedMeetingArtifactTabLabel()')
    expect(source).toContain("key: 'summary'")
    expect(source).toContain("key: 'ask'")
    expect(source).toContain(':compact-header="isCompactEndedMeetingMobileLayout"')
    expect(source).toContain('@generate-summary="triggerSummaryGeneration"')
    expect(source).toContain('@generate-transcript="triggerTranscriptGeneration"')
    expect(source).toContain('@ask-question="submitMeetingQuestion"')
    expect(source).toContain('@pause-recording="pauseTranscriptionRecording"')
    expect(source).toContain('@resume-recording="resumeTranscriptionRecording"')
    expect(source).toContain('class="artifact-status-list"')
    expect(source).toContain('class="artifact-status-meta"')
    expect(source).toContain('data-testid="meeting-admin-artifact-menu-trigger"')
    expect(source).toContain('data-testid="meeting-admin-artifact-menu"')
    expect(source).toContain('data-testid="meeting-admin-regenerate-transcript"')
    expect(source).toContain('data-testid="meeting-admin-regenerate-summary"')
    expect(source).toContain('data-testid="meeting-admin-download-audio"')
    expect(source).not.toContain(':type="artifactStatusType(artifact.status)"')
    expect(source).not.toContain('artifactStatusType(status)')
    expect(source).not.toContain('class="summary-panel"')
    expect(source).not.toContain('class="transcript-panel"')
    expect(source).not.toContain('class="ask-meeting-panel"')
  })

  it('keeps the compact ended-meeting artifact menu unchanged while only restyling the header overflow menu', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain('data-testid="meeting-ended-actions-menu"')
    expect(source).toContain('data-testid="meeting-ended-action-summary"')
    expect(source).toContain('data-testid="meeting-ended-action-transcript"')
    expect(source).toContain('data-testid="meeting-ended-action-ask"')
    expect(source).toContain('data-testid="meeting-ended-action-chat"')
    expect(source).toContain('data-testid="meeting-mobile-overflow-menu"')
    expect(source).toContain('meeting-header-compact-menu')
    expect(source).toContain('@click="showEndedMeetingCompactMenu = true"')
    expect(source).toContain('<n-modal')
    expect(source).toContain('v-model:show="showEndedMeetingCompactMenu"')
  })

  it('shows the compact ended-meeting action menu as a wide mobile bottom sheet', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain('data-testid="meeting-ended-actions-sheet"')
    expect(source).toContain('data-testid="meeting-ended-actions-sheet-close"')
    expect(source).toContain('.meeting-ended-actions-sheet {')
    expect(source).toContain('width: min(100vw, 420px);')
    expect(source).toContain('margin: 0 auto;')
    expect(source).toContain('max-height: calc(100dvh - 16px);')
    expect(source).toContain('border-radius: 16px 16px 0 0;')
    expect(source).toContain('.meeting-ended-actions-sheet .meeting-ended-action-menu {')
    expect(source).toContain('width: 100%;')
    expect(source).toContain('.meeting-ended-menu-action-label {')
    expect(source).toContain('white-space: nowrap;')
  })

  it('keeps store mutations, share side effects, and summary payload assembly in the view', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain('triggerSummaryGeneration(options = {})')
    expect(source).toContain('triggerTranscriptGeneration(options = {})')
    expect(source).toContain('this.meetingsStore.generateSummary(this.meeting.id, {')
    expect(source).toContain('this.meetingsStore.generateTranscript(this.meeting.id, {')
    expect(source).toContain('triggerAdminSummaryRegeneration()')
    expect(source).toContain('triggerAdminTranscriptRegeneration()')
    expect(source).toContain("reason: 'admin_regenerate'")
    expect(source).toContain('downloadMeetingAudio()')
    expect(source).toContain("api.get(`/meetings/${this.meeting.id}/audio`, {")
    expect(source).toContain('copySummary()')
    expect(source).toContain('exportSummary()')
    expect(source).toContain('shareSummaryInApp()')
    expect(source).toContain('Meeting: ${this.meetingShareLink}')
    expect(source).toContain('loadedMeetingChatMessages()')
  })

  it('shows attended participants, uses ended meeting engagement counts, and prepends a meeting link in shared summaries', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain('meetingVoiceParticipants() {')
    expect(source).toContain('visibleMeetingParticipants()')
    expect(source).toContain("participant.invite_status !== 'joined'")
    expect(source).toContain('&& !participant?.chat_last_read_at')
    expect(source).toContain('for (const participant of this.meetingVoiceParticipants)')
    expect(source).toContain('attendedParticipantDisplayNames()')
    expect(source).toContain('countMeetingEngagedParticipants(this.meeting)')
    expect(source).toContain('return this.visibleMeetingParticipants.length')
    expect(source).toContain('Meeting: ${this.meetingShareLink}')
  })

  it('tracks mobile layout and switches ended-meeting surfaces for evidence navigation', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain("import { observeMobileLayout, readIsMobileLayout } from '../lib/mobile-layout.js'")
    expect(source).toContain('isMobileLayout: readIsMobileLayout()')
    expect(source).toContain('const SHORT_VIEWPORT_HEIGHT = 760')
    expect(source).toContain('readIsShortViewport(win = window)')
    expect(source).toContain('observeShortViewport(callback, win = window)')
    expect(source).toContain('isShortViewport: readIsShortViewport()')
    expect(source).toContain('stopObservingShortViewport: null')
    expect(source).toContain('isShortEndedMeetingViewport()')
    expect(source).toContain('this.stopObservingShortViewport = observeShortViewport((matches) => {')
    expect(source).toContain('this.stopObservingShortViewport?.()')
    expect(source).toContain('selectedMeetingVideoParticipantId: null')
    expect(source).toContain('endedMeetingArtifactTab: null')
    expect(source).toContain('isEndedMeetingChatOpen: false')
    expect(source).toContain('resolvedMeetingFocusParticipantId()')
    expect(source).toContain('clearMeetingVideoParticipantSelection()')
    expect(source).toContain('follow_active_speaker')
    expect(source).toContain('focusEvidenceSurface(evidence)')
    expect(source).toContain("this.focusEvidenceSurface({ type: 'chat', message_id: messageId })")
    expect(source).toContain("this.focusEvidenceSurface({ type: 'transcript', start_ms: transcriptStartMs })")
    expect(source).toContain("'$route.query.transcript_start_ms'")
    expect(source).toContain('highlightedTranscriptStartMs')
    expect(source).toContain('scrollHighlightedTranscriptIntoView()')
    expect(source).toContain('this.$refs.endedTranscriptPanel || this.$refs.inlineTranscriptPanel')
    expect(source).toContain("'$route.query.message'")
    expect(source).toContain('this.messagesStore.setHighlightedMessage(messageId)')
    expect(source).toContain('await this.messagesStore.loadAroundMessage(messageId, {')
    expect(source).toContain("query.message = evidence.message_id")
  })

  it('delegates member-panel toggling to the shared workspace shell', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain('emits: [\'toggle-members\']')
    expect(source).toContain('@click="$emit(\'toggle-members\')"')
    expect(source).not.toContain('meeting-mobile-sidebar-drawer')
    expect(source).not.toContain('meeting-mobile-members-drawer')
  })

  it('clears the active meeting context only when navigating away from meeting routes', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain("shouldPreserveMeetingContextRoute(route)")
    expect(source).toContain("return route?.name === 'Meeting' || route?.name === 'MeetingScreenShare'")
    expect(source).toContain('this.meetingsStore.clearActive()')
    expect(source).toContain('beforeRouteLeave(to, from, next)')
  })

  it('supports scheduled meeting controls, guest links, and ICS downloads', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain("CloseOutline")
    expect(source).toContain("EllipsisHorizontalOutline as MoreIcon")
    expect(source).toContain("ArrowUndoOutline as BackIcon")
    expect(source).toContain("LanguageOutline as LanguageIcon")
    expect(source).toContain("PencilOutline as EditIcon")
    expect(source).toContain("PeopleOutline as PeopleIcon")
    expect(source).toContain("VideocamOutline as VideocamIcon")
    expect(source).toContain("import { getEffectiveMeetingStatus, isOverdueScheduledMeeting } from '../lib/meeting-lifecycle.js'")
    expect(source).toContain('meetingStatusLabel')
    expect(source).toContain('effectiveMeetingStatus()')
    expect(source).toContain('isOverdueScheduledMeeting()')
    expect(source).toContain('meetingScheduleMeta')
    expect(source).toContain('meetingLanguageLabel')
    expect(source).toContain("label: this.$t('ui.views.meeting_language')")
    expect(source).toContain('canRescheduleMeeting')
    expect(source).toContain('canEditMeetingLanguage')
    expect(source).toContain('showLanguageModal')
    expect(source).toContain('saveMeetingLanguage()')
    expect(source).toContain("this.meetingsStore.setLanguage(this.meeting.id, this.languageForm.language)")
    expect(source).toContain("this.$t('ui.views.meeting_language_updated_regeneration_required')")
    expect(source).toContain("this.$t('ui.views.meeting_language_updated')")
    expect(source).toContain("ui.views.change_meeting_language")
    expect(source).toContain('createGuestInviteLink')
    expect(source).toContain('copyGuestInviteLink')
    expect(source).toContain('revokeGuestInviteLink')
    expect(source).toContain('meetingInviteLinkBannerDismissed: false')
    expect(source).toContain('showMeetingInviteLinkBanner()')
    expect(source).toContain('meetingInviteLinkBannerKey()')
    expect(source).toContain("meetingInviteLinkBannerKey(newKey, oldKey)")
    expect(source).toContain('dismissMeetingInviteLinkBanner()')
    expect(source).toContain("@click=\"dismissMeetingInviteLinkBanner\"")
    expect(source).toContain(":aria-label=\"$t('common.close')\"")
    expect(source).toContain('<n-icon size="14"><close-outline /></n-icon>')
    expect(source).toContain('downloadMeetingIcs')
    expect(source).toContain('downloadingMeetingAudio: false')
    expect(source).toContain('showAdminArtifactMenu: false')
    expect(source).toContain('adminArtifactMenu()')
    expect(source).toContain('showEndedMeetingAdminMenu()')
    expect(source).toContain('meeting_admin_artifact_actions')
    expect(source).toContain('download_meeting_audio')
    expect(source).toContain('regenerate_summary')
    expect(source).toContain('regenerate_transcript')
    expect(source).toContain('showRescheduleModal')
    expect(source).toContain('rescheduleForm.language')
    expect(source).toContain("this.effectiveMeetingStatus === 'scheduled'")
  })

  it('hides ended-meeting in-app summary sharing for guest users while keeping the member flow guarded in the view', () => {
    const source = readFileSync(resolve('src/views/MeetingView.vue'), 'utf8')

    expect(source).toContain(':can-share-in-app="canShareSummaryInApp"')
    expect(source).toContain('canShareSummaryInApp()')
    expect(source).toContain("return this.sessionStore.user?.account_type !== 'guest'")
    expect(source).toContain('if (!this.summaryShareText || !this.canShareSummaryInApp) return')
    expect(source).toContain('if (!this.canShareSummaryInApp || !this.shareSummaryTargetChannelId || !this.summaryShareText) return')
  })
})
