import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WorkspaceShell', () => {
  it('keeps channels and meetings under one authenticated parent shell', () => {
    const shellSource = readFileSync(resolve('src/views/WorkspaceShell.vue'), 'utf8')
    const routerSource = readFileSync(resolve('src/router/index.js'), 'utf8')

    expect(routerSource).toContain("component: () => import('../views/WorkspaceShell.vue')")
    expect(routerSource).toContain("path: 'channels/:channelId?'")
    expect(routerSource).toContain("path: 'meetings/:meetingId'")
    expect(shellSource).toContain('<router-view v-if="sessionReady" v-slot="{ Component }">')
    expect(shellSource).toContain(':show-members="rightPanelMode === \'members\'"')
    expect(shellSource).toContain(':right-panel-mode="rightPanelMode"')
    expect(shellSource).toContain("@toggle-members=\"toggleRightPanel('members')\"")
    expect(shellSource).toContain("@toggle-past-meetings=\"toggleRightPanel('pastMeetings')\"")
  })

  it('owns the shared top bar, mobile drawers, and global overlays for both workspace contexts', () => {
    const shellSource = readFileSync(resolve('src/views/WorkspaceShell.vue'), 'utf8')

    expect(shellSource).toContain("import {\n  buildMobileSidebarClosedLocation,")
    expect(shellSource).toContain('mobileNavTestId()')
    expect(shellSource).toContain('mobileSidebarDrawerTestId()')
    expect(shellSource).toContain('mobileMembersDrawerTestId()')
    expect(shellSource).toContain('showMobileSidebar()')
    expect(shellSource).toContain("&& isMobileSidebarRouteOpen(this.$route)")
    expect(shellSource).toContain('suppressNextMobileSidebarClose: false')
    expect(shellSource).toContain('async onChannelSelected(targetRoute)')
    expect(shellSource).toContain('const resolvedTarget = this.$router.resolve(targetRoute)')
    expect(shellSource).toContain('const action = resolveMobileSidebarSelectionAction(this.$route, resolvedTarget, {')
    expect(shellSource).toContain("if (action.mode === 'transfer') {")
    expect(shellSource).toContain('await this.$router.replace(action.openTo).catch(() => {})')
    expect(shellSource).toContain('await this.$router.push(action.closedTo).catch(() => {})')
    expect(shellSource).toContain('await this.$router.push(action.to).catch(() => {})')
    expect(shellSource).toContain('async openMobileSidebar()')
    expect(shellSource).toContain('closeMobileSidebar({ forceReplace = false } = {})')
    expect(shellSource).toContain('onMobileSidebarVisibilityChange(value)')
    expect(shellSource).toContain('const target = buildMobileSidebarOpenLocation(this.$route)')
    expect(shellSource).not.toContain('buildMobileSidebarOpenLocation(this.$route, {')
    expect(shellSource).toContain("await this.$router.push(target).catch(() => {})")
    expect(shellSource).toContain("this.$router.replace(buildMobileSidebarClosedLocation(this.$route)).catch(() => {})")
    expect(shellSource).toContain('const action = resolveMobileSidebarCloseAction(this.$route, {')
    expect(shellSource).toContain('this.$router.back()')
    expect(shellSource).toContain('this.suppressNextMobileSidebarClose = true')
    expect(shellSource).toContain('if (this.suppressNextMobileSidebarClose) {')
    expect(shellSource).toContain('this.suppressNextMobileSidebarClose = false')
    expect(shellSource).toContain('showMobileRightPanel: {')
    expect(shellSource).toContain("return this.isMobileLayout && this.rightPanelMode !== 'closed'")
    expect(shellSource).toContain("return this.rightPanelMode === 'pastMeetings' ? 340 : 260")
    expect(shellSource).toContain("return this.$t('ui.views.past_meetings')")
    expect(shellSource).toContain('<ChannelPastMeetingsPanel')
    expect(shellSource).toContain(":data-testid=\"mobileNavTestId\"")
    expect(shellSource).toContain(":data-testid=\"mobileSidebarDrawerTestId\"")
    expect(shellSource).toContain(":data-testid=\"mobileMembersDrawerTestId\"")
    expect(shellSource).toContain(':show="showMobileSidebar"')
    expect(shellSource).toContain('@update:show="onMobileSidebarVisibilityChange"')
    expect(shellSource).toContain(':width="320"')
    expect(shellSource).toContain('<ChannelSidebar @channel-selected="onChannelSelected" />')
    expect(shellSource).toContain('<PinnedMessages v-if="showPinnedMessagesPanel" />')
    expect(shellSource).toContain('<ForwardMessageModal v-if="showForwardMessageModal" />')
    expect(shellSource).toContain('<GlobalSearchDialog />')
    expect(shellSource).toContain('<VoiceSettings />')
    expect(shellSource).toContain('<SponsorshipPrompt')
    expect(shellSource).toContain(':show="uiStore.showSponsorshipPrompt"')
    expect(shellSource).toContain('@close="closeSponsorshipPrompt"')
    expect(shellSource).toContain("claimSponsorshipPrompt as claimSponsorshipPromptRequest")
    expect(shellSource).toContain('this.sessionStore.user?.is_primary_admin !== true')
    expect(shellSource).toContain('result?.show === true')
    expect(shellSource).toContain('this.uiStore.openSponsorshipPrompt()')
  })

  it('reduces the workspace chrome for guest sessions while owning the floating guest voice dock', () => {
    const shellSource = readFileSync(resolve('src/views/WorkspaceShell.vue'), 'utf8')

    expect(shellSource).toContain("isGuestUser()")
    expect(shellSource).toContain('v-if="isMobileLayout && !isGuestUser"')
    expect(shellSource).toContain('v-if="!isMobileLayout && !isGuestUser" class="sidebar"')
    expect(shellSource).toContain('v-if="!isGuestUser"')
    expect(shellSource).toContain('if (this.isGuestUser) return')
    expect(shellSource).toContain('voiceStore()')
    expect(shellSource).toContain('return useVoiceStore()')
    expect(shellSource).toContain('showGuestVoiceDock()')
    expect(shellSource).toContain('return this.isGuestUser && !!this.voiceStore.channelId')
    expect(shellSource).toContain('<VoiceControls v-if="showGuestVoiceDock" variant="floating" />')
    expect(shellSource).toContain('closeSponsorshipPrompt()')
    expect(shellSource).toContain('this.uiStore.closeSponsorshipPrompt()')
  })
})
