import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('PlatformSettings source contract', () => {
  it('includes controls for default language, default meeting language, and auto-away timeout', () => {
    const source = readFileSync(resolve('src/components/admin/PlatformSettings.vue'), 'utf8')

    expect(source).toContain('data-testid="platform-default-language"')
    expect(source).toContain('data-testid="platform-auto-away-minutes"')
    expect(source).toContain('data-testid="platform-upload-max-file-size-mb"')
    expect(source).toContain('data-testid="platform-image-upload-max-dimension-px"')
    expect(source).toContain('data-testid="platform-image-upload-quality"')
    expect(source).toContain('data-testid="platform-klipy-api-key"')
    expect(source).toContain('data-testid="platform-klipy-status"')
    expect(source).toContain('data-testid="platform-klipy-clear"')
    expect(source).not.toContain('data-testid="platform-theme-mode-default"')
    expect(source).not.toContain('data-testid="platform-theme-dark-primary-color"')
    expect(source).not.toContain('data-testid="design-global-custom-css"')
    expect(source).toContain('autoAwayMinutes: 15')
    expect(source).toContain('uploadMaxFileSizeMb: DEFAULT_UPLOAD_MAX_FILE_SIZE_MB')
    expect(source).toContain('imageUploadMaxDimensionPx: DEFAULT_IMAGE_UPLOAD_MAX_DIMENSION_PX')
    expect(source).toContain('imageUploadQuality: DEFAULT_IMAGE_UPLOAD_QUALITY')
    expect(source).toContain("klipyApiKey: ''")
    expect(source).toContain('klipyConfigured: false')
    expect(source).toContain('clearingKlipyApiKey: false')
    expect(source).toContain('Math.max(1, Number.parseInt(this.autoAwayMinutes, 10) || 15)')
    expect(source).not.toContain('defaultMeetingLanguage')
    expect(source).not.toContain('meetingVideoEnabled')
    expect(source).not.toContain('defaultMeetingHistoryAccess')
    expect(source).not.toContain('...themePayload')
    expect(source).not.toContain('this.themeStore.setPlatformThemeSettings(settings)')
    expect(source).toContain('uploadMaxFileSizeMb')
    expect(source).toContain('imageUploadMaxDimensionPx')
    expect(source).toContain('imageUploadQuality')
    expect(source).toContain('payload.klipyApiKey = klipyApiKey')
    expect(source).toContain('this.klipyApiKey = \'\'')
    expect(source).toContain('clearKlipyApiKey: true')
    expect(source).toContain('async clearKlipyApiKey()')
    expect(source).toContain('klipy_configured')
    expect(source).toContain("ui.components.admin.platform_settings_updated")
    expect(source).toContain('data-testid="platform-sponsorship-prompts-enabled"')
    expect(source).toContain('data-testid="platform-sponsorship-prompt-preview"')
    expect(source).toContain('isPrimaryAdmin()')
    expect(source).toContain('uiStore()')
    expect(source).toContain('showSponsorshipPromptPreview()')
    expect(source).toContain('this.uiStore.openSponsorshipPrompt()')
    expect(source).not.toContain('claimSponsorshipPrompt')
    expect(source).toContain('getSponsorshipPromptPreference()')
    expect(source).toContain('updateSponsorshipPromptPreference(enabled)')
  })
})
