export const emojiCategories = [
  {
    name: 'smileys',
    label: 'Smileys',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'grinning face', keywords: ['happy', 'smile', 'joy'] },
      { emoji: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'smile'] },
      { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'laugh'] },
      { emoji: '😁', name: 'beaming face', keywords: ['grin', 'happy'] },
      { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'happy'] },
      { emoji: '😅', name: 'grinning face with sweat', keywords: ['relief', 'nervous'] },
      { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['lol', 'rofl'] },
      { emoji: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'lol'] },
      { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile'] },
      { emoji: '🙃', name: 'upside-down face', keywords: ['sarcasm', 'silly'] },
      { emoji: '😉', name: 'winking face', keywords: ['wink', 'flirt'] },
      { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'happy'] },
      { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
      { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore'] },
      { emoji: '😍', name: 'heart eyes', keywords: ['love', 'crush'] },
      { emoji: '🤩', name: 'star-struck', keywords: ['wow', 'excited'] },
      { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'] },
      { emoji: '😗', name: 'kissing face', keywords: ['kiss'] },
      { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss'] },
      { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'] },
      { emoji: '🥲', name: 'smiling face with tear', keywords: ['sad', 'happy'] },
      { emoji: '😋', name: 'face savoring food', keywords: ['yummy', 'delicious'] },
      { emoji: '😛', name: 'face with tongue', keywords: ['playful', 'silly'] },
      { emoji: '😜', name: 'winking face with tongue', keywords: ['playful', 'joke'] },
      { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'wild'] },
      { emoji: '😝', name: 'squinting face with tongue', keywords: ['playful'] },
      { emoji: '🤑', name: 'money-mouth face', keywords: ['rich', 'money'] },
      { emoji: '🤗', name: 'hugging face', keywords: ['hug', 'warm'] },
      { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle'] },
      { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'] },
      { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm'] },
      { emoji: '🫡', name: 'saluting face', keywords: ['salute', 'respect'] },
      { emoji: '🤐', name: 'zipper-mouth face', keywords: ['secret', 'mute'] },
      { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['skeptical', 'doubt'] },
      { emoji: '😐', name: 'neutral face', keywords: ['meh', 'blank'] },
      { emoji: '😑', name: 'expressionless face', keywords: ['blank', 'unamused'] },
      { emoji: '😶', name: 'face without mouth', keywords: ['speechless', 'silence'] },
      { emoji: '🫠', name: 'melting face', keywords: ['melt', 'hot'] },
      { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'suggestive'] },
      { emoji: '😒', name: 'unamused face', keywords: ['meh', 'bored'] },
      { emoji: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'annoyed'] },
      { emoji: '😬', name: 'grimacing face', keywords: ['awkward', 'nervous'] },
      { emoji: '😮‍💨', name: 'face exhaling', keywords: ['sigh', 'relief'] },
      { emoji: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio'] },
      { emoji: '😌', name: 'relieved face', keywords: ['relief', 'calm'] },
      { emoji: '😔', name: 'pensive face', keywords: ['sad', 'thoughtful'] },
      { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleepy'] },
      { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'hungry'] },
      { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz'] },
      { emoji: '😷', name: 'face with medical mask', keywords: ['sick', 'mask'] },
      { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'] },
      { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injury'] },
      { emoji: '🤢', name: 'nauseated face', keywords: ['sick', 'gross'] },
      { emoji: '🤮', name: 'face vomiting', keywords: ['sick', 'throw up'] },
      { emoji: '🥵', name: 'hot face', keywords: ['hot', 'sweating'] },
      { emoji: '🥶', name: 'cold face', keywords: ['cold', 'freezing'] },
      { emoji: '🥴', name: 'woozy face', keywords: ['dizzy', 'drunk'] },
      { emoji: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy', 'dead'] },
      { emoji: '🤯', name: 'exploding head', keywords: ['mindblown', 'shocked'] },
      { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'western'] },
      { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate'] },
      { emoji: '🥸', name: 'disguised face', keywords: ['disguise', 'incognito'] },
      { emoji: '😎', name: 'face with sunglasses', keywords: ['cool', 'sunglasses'] },
      { emoji: '🤓', name: 'nerd face', keywords: ['nerd', 'geek'] },
      { emoji: '🧐', name: 'face with monocle', keywords: ['inspect', 'curious'] },
      { emoji: '😕', name: 'confused face', keywords: ['confused', 'unsure'] },
      { emoji: '🫤', name: 'face with diagonal mouth', keywords: ['meh', 'unsure'] },
      { emoji: '😟', name: 'worried face', keywords: ['worried', 'concern'] },
      { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'] },
      { emoji: '😮', name: 'face with open mouth', keywords: ['surprised', 'wow'] },
      { emoji: '😯', name: 'hushed face', keywords: ['surprised', 'quiet'] },
      { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'amazed'] },
      { emoji: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'] },
      { emoji: '🥺', name: 'pleading face', keywords: ['puppy eyes', 'please'] },
      { emoji: '🥹', name: 'face holding back tears', keywords: ['touched', 'emotional'] },
      { emoji: '😦', name: 'frowning face with open mouth', keywords: ['shocked', 'sad'] },
      { emoji: '😧', name: 'anguished face', keywords: ['pain', 'distress'] },
      { emoji: '😨', name: 'fearful face', keywords: ['scared', 'fear'] },
      { emoji: '😰', name: 'anxious face with sweat', keywords: ['nervous', 'anxious'] },
      { emoji: '😥', name: 'sad but relieved face', keywords: ['sad', 'relief'] },
      { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'] },
      { emoji: '😭', name: 'loudly crying face', keywords: ['sob', 'cry', 'sad'] },
      { emoji: '😱', name: 'face screaming in fear', keywords: ['scream', 'horror'] },
      { emoji: '😖', name: 'confounded face', keywords: ['frustrated', 'upset'] },
      { emoji: '😣', name: 'persevering face', keywords: ['struggle', 'effort'] },
      { emoji: '😞', name: 'disappointed face', keywords: ['sad', 'disappointed'] },
      { emoji: '😓', name: 'downcast face with sweat', keywords: ['tired', 'stressed'] },
      { emoji: '😩', name: 'weary face', keywords: ['tired', 'exhausted'] },
      { emoji: '😫', name: 'tired face', keywords: ['exhausted', 'fed up'] },
      { emoji: '🥱', name: 'yawning face', keywords: ['yawn', 'bored', 'tired'] },
      { emoji: '😤', name: 'face with steam from nose', keywords: ['angry', 'frustrated'] },
      { emoji: '😡', name: 'pouting face', keywords: ['angry', 'rage', 'mad'] },
      { emoji: '😠', name: 'angry face', keywords: ['angry', 'mad'] },
      { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['swearing', 'cursing'] },
      { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil'] },
      { emoji: '👿', name: 'angry face with horns', keywords: ['devil', 'angry'] },
      { emoji: '💀', name: 'skull', keywords: ['death', 'dead', 'skeleton'] },
      { emoji: '☠️', name: 'skull and crossbones', keywords: ['danger', 'death'] },
      { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'crap'] },
      { emoji: '🤡', name: 'clown face', keywords: ['clown', 'funny'] },
      { emoji: '👹', name: 'ogre', keywords: ['monster', 'scary'] },
      { emoji: '👻', name: 'ghost', keywords: ['ghost', 'halloween', 'boo'] },
      { emoji: '👽', name: 'alien', keywords: ['alien', 'ufo', 'space'] },
      { emoji: '🤖', name: 'robot', keywords: ['robot', 'bot', 'ai'] },
      { emoji: '🫶', name: 'heart hands', keywords: ['love', 'heart'] }
    ]
  },
  {
    name: 'gestures',
    label: 'Gesten',
    icon: '👍',
    emojis: [
      { emoji: '👋', name: 'waving hand', keywords: ['hello', 'goodbye', 'wave'] },
      { emoji: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'] },
      { emoji: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'five'] },
      { emoji: '✋', name: 'raised hand', keywords: ['hand', 'stop', 'high five'] },
      { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek'] },
      { emoji: '🫱', name: 'rightwards hand', keywords: ['hand', 'right'] },
      { emoji: '🫲', name: 'leftwards hand', keywords: ['hand', 'left'] },
      { emoji: '👌', name: 'OK hand', keywords: ['ok', 'perfect'] },
      { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'what'] },
      { emoji: '🤏', name: 'pinching hand', keywords: ['small', 'tiny'] },
      { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'victory', 'two'] },
      { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
      { emoji: '🫰', name: 'hand with index finger and thumb crossed', keywords: ['money', 'snap'] },
      { emoji: '🤟', name: 'love-you gesture', keywords: ['love', 'rock'] },
      { emoji: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal'] },
      { emoji: '🤙', name: 'call me hand', keywords: ['call', 'hang loose'] },
      { emoji: '👈', name: 'backhand index pointing left', keywords: ['left', 'point'] },
      { emoji: '👉', name: 'backhand index pointing right', keywords: ['right', 'point'] },
      { emoji: '👆', name: 'backhand index pointing up', keywords: ['up', 'point'] },
      { emoji: '🖕', name: 'middle finger', keywords: ['flip off', 'rude'] },
      { emoji: '👇', name: 'backhand index pointing down', keywords: ['down', 'point'] },
      { emoji: '☝️', name: 'index pointing up', keywords: ['up', 'point', 'one'] },
      { emoji: '🫵', name: 'index pointing at the viewer', keywords: ['you', 'point'] },
      { emoji: '👍', name: 'thumbs up', keywords: ['like', 'good', 'ok', 'yes'] },
      { emoji: '👎', name: 'thumbs down', keywords: ['dislike', 'bad', 'no'] },
      { emoji: '✊', name: 'raised fist', keywords: ['fist', 'power'] },
      { emoji: '👊', name: 'oncoming fist', keywords: ['punch', 'fist bump'] },
      { emoji: '🤛', name: 'left-facing fist', keywords: ['fist bump'] },
      { emoji: '🤜', name: 'right-facing fist', keywords: ['fist bump'] },
      { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'] },
      { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray'] },
      { emoji: '🫶', name: 'heart hands', keywords: ['love', 'heart'] },
      { emoji: '👐', name: 'open hands', keywords: ['open', 'jazz hands'] },
      { emoji: '🤲', name: 'palms up together', keywords: ['pray', 'receive'] },
      { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree', 'handshake'] },
      { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks'] },
      { emoji: '✍️', name: 'writing hand', keywords: ['write', 'note'] },
      { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'flex'] },
      { emoji: '🦾', name: 'mechanical arm', keywords: ['robot', 'prosthetic'] },
      { emoji: '🫂', name: 'people hugging', keywords: ['hug', 'embrace'] }
    ]
  },
  {
    name: 'hearts',
    label: 'Herzen',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', name: 'red heart', keywords: ['love', 'heart'] },
      { emoji: '🧡', name: 'orange heart', keywords: ['love', 'heart'] },
      { emoji: '💛', name: 'yellow heart', keywords: ['love', 'heart'] },
      { emoji: '💚', name: 'green heart', keywords: ['love', 'heart'] },
      { emoji: '💙', name: 'blue heart', keywords: ['love', 'heart'] },
      { emoji: '💜', name: 'purple heart', keywords: ['love', 'heart'] },
      { emoji: '🖤', name: 'black heart', keywords: ['love', 'heart', 'dark'] },
      { emoji: '🤍', name: 'white heart', keywords: ['love', 'heart', 'pure'] },
      { emoji: '🤎', name: 'brown heart', keywords: ['love', 'heart'] },
      { emoji: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad'] },
      { emoji: '❤️‍🔥', name: 'heart on fire', keywords: ['love', 'passion'] },
      { emoji: '❤️‍🩹', name: 'mending heart', keywords: ['healing', 'recovery'] },
      { emoji: '💕', name: 'two hearts', keywords: ['love', 'hearts'] },
      { emoji: '💞', name: 'revolving hearts', keywords: ['love', 'hearts'] },
      { emoji: '💓', name: 'beating heart', keywords: ['love', 'heartbeat'] },
      { emoji: '💗', name: 'growing heart', keywords: ['love', 'heart'] },
      { emoji: '💖', name: 'sparkling heart', keywords: ['love', 'heart', 'sparkle'] },
      { emoji: '💘', name: 'heart with arrow', keywords: ['love', 'cupid'] },
      { emoji: '💝', name: 'heart with ribbon', keywords: ['love', 'gift'] },
      { emoji: '🔥', name: 'fire', keywords: ['fire', 'hot', 'lit'] },
      { emoji: '⭐', name: 'star', keywords: ['star', 'favorite'] },
      { emoji: '🌟', name: 'glowing star', keywords: ['star', 'shine'] },
      { emoji: '✨', name: 'sparkles', keywords: ['sparkle', 'magic', 'clean'] },
      { emoji: '💫', name: 'dizzy', keywords: ['star', 'dizzy'] },
      { emoji: '💯', name: 'hundred points', keywords: ['perfect', '100', 'score'] },
      { emoji: '💢', name: 'anger symbol', keywords: ['angry', 'rage'] },
      { emoji: '💥', name: 'collision', keywords: ['boom', 'explosion'] },
      { emoji: '💦', name: 'sweat droplets', keywords: ['sweat', 'water'] },
      { emoji: '💨', name: 'dashing away', keywords: ['wind', 'fast', 'run'] }
    ]
  },
  {
    name: 'animals',
    label: 'Tiere',
    icon: '🐱',
    emojis: [
      { emoji: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet'] },
      { emoji: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet'] },
      { emoji: '🐭', name: 'mouse face', keywords: ['mouse', 'rodent'] },
      { emoji: '🐹', name: 'hamster', keywords: ['hamster', 'pet'] },
      { emoji: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny'] },
      { emoji: '🦊', name: 'fox', keywords: ['fox', 'clever'] },
      { emoji: '🐻', name: 'bear', keywords: ['bear', 'teddy'] },
      { emoji: '🐼', name: 'panda', keywords: ['panda', 'bear'] },
      { emoji: '🐨', name: 'koala', keywords: ['koala', 'australia'] },
      { emoji: '🐯', name: 'tiger face', keywords: ['tiger', 'cat'] },
      { emoji: '🦁', name: 'lion', keywords: ['lion', 'king'] },
      { emoji: '🐮', name: 'cow face', keywords: ['cow', 'moo'] },
      { emoji: '🐷', name: 'pig face', keywords: ['pig', 'oink'] },
      { emoji: '🐸', name: 'frog', keywords: ['frog', 'toad'] },
      { emoji: '🐵', name: 'monkey face', keywords: ['monkey', 'ape'] },
      { emoji: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'hide', 'shy'] },
      { emoji: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'deaf'] },
      { emoji: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'mute', 'secret'] },
      { emoji: '🐔', name: 'chicken', keywords: ['chicken', 'hen'] },
      { emoji: '🐧', name: 'penguin', keywords: ['penguin', 'cold'] },
      { emoji: '🐦', name: 'bird', keywords: ['bird', 'tweet'] },
      { emoji: '🦅', name: 'eagle', keywords: ['eagle', 'bird'] },
      { emoji: '🦆', name: 'duck', keywords: ['duck', 'quack'] },
      { emoji: '🦉', name: 'owl', keywords: ['owl', 'wise'] },
      { emoji: '🐺', name: 'wolf', keywords: ['wolf', 'howl'] },
      { emoji: '🐗', name: 'boar', keywords: ['boar', 'pig'] },
      { emoji: '🐴', name: 'horse face', keywords: ['horse', 'pony'] },
      { emoji: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic', 'fantasy'] },
      { emoji: '🐝', name: 'honeybee', keywords: ['bee', 'honey'] },
      { emoji: '🐛', name: 'bug', keywords: ['bug', 'insect'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['butterfly', 'pretty'] },
      { emoji: '🐌', name: 'snail', keywords: ['snail', 'slow'] },
      { emoji: '🐙', name: 'octopus', keywords: ['octopus', 'sea'] },
      { emoji: '🐬', name: 'dolphin', keywords: ['dolphin', 'sea'] },
      { emoji: '🐳', name: 'spouting whale', keywords: ['whale', 'sea'] },
      { emoji: '🦈', name: 'shark', keywords: ['shark', 'danger'] },
      { emoji: '🐊', name: 'crocodile', keywords: ['crocodile', 'alligator'] },
      { emoji: '🐘', name: 'elephant', keywords: ['elephant', 'big'] },
      { emoji: '🦒', name: 'giraffe', keywords: ['giraffe', 'tall'] },
      { emoji: '🐍', name: 'snake', keywords: ['snake', 'serpent'] }
    ]
  },
  {
    name: 'food',
    label: 'Essen',
    icon: '🍕',
    emojis: [
      { emoji: '🍎', name: 'red apple', keywords: ['apple', 'fruit'] },
      { emoji: '🍐', name: 'pear', keywords: ['pear', 'fruit'] },
      { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'fruit'] },
      { emoji: '🍋', name: 'lemon', keywords: ['lemon', 'sour'] },
      { emoji: '🍌', name: 'banana', keywords: ['banana', 'fruit'] },
      { emoji: '🍉', name: 'watermelon', keywords: ['watermelon', 'fruit'] },
      { emoji: '🍇', name: 'grapes', keywords: ['grapes', 'wine', 'fruit'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['strawberry', 'berry'] },
      { emoji: '🫐', name: 'blueberries', keywords: ['blueberry', 'berry'] },
      { emoji: '🍑', name: 'peach', keywords: ['peach', 'fruit'] },
      { emoji: '🍒', name: 'cherries', keywords: ['cherry', 'fruit'] },
      { emoji: '🥑', name: 'avocado', keywords: ['avocado', 'guacamole'] },
      { emoji: '🍕', name: 'pizza', keywords: ['pizza', 'food'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'food'] },
      { emoji: '🍟', name: 'french fries', keywords: ['fries', 'food'] },
      { emoji: '🌭', name: 'hot dog', keywords: ['hotdog', 'food'] },
      { emoji: '🍿', name: 'popcorn', keywords: ['popcorn', 'movie'] },
      { emoji: '🧁', name: 'cupcake', keywords: ['cupcake', 'cake'] },
      { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'] },
      { emoji: '🎂', name: 'birthday cake', keywords: ['birthday', 'cake', 'celebrate'] },
      { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'sweet'] },
      { emoji: '🍪', name: 'cookie', keywords: ['cookie', 'sweet'] },
      { emoji: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'sweet'] },
      { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'drink'] },
      { emoji: '🍵', name: 'teacup', keywords: ['tea', 'drink'] },
      { emoji: '🥤', name: 'cup with straw', keywords: ['drink', 'soda'] },
      { emoji: '🍺', name: 'beer mug', keywords: ['beer', 'drink', 'prost'] },
      { emoji: '🍻', name: 'clinking beer mugs', keywords: ['beer', 'cheers', 'prost'] },
      { emoji: '🥂', name: 'clinking glasses', keywords: ['champagne', 'cheers', 'toast'] },
      { emoji: '🍷', name: 'wine glass', keywords: ['wine', 'drink'] },
      { emoji: '🥃', name: 'tumbler glass', keywords: ['whiskey', 'drink'] },
      { emoji: '🧃', name: 'beverage box', keywords: ['juice', 'drink'] },
      { emoji: '🍽️', name: 'fork and knife with plate', keywords: ['dining', 'food'] },
      { emoji: '🥡', name: 'takeout box', keywords: ['takeout', 'food'] },
      { emoji: '🍳', name: 'cooking', keywords: ['egg', 'frying', 'breakfast'] }
    ]
  },
  {
    name: 'objects',
    label: 'Objekte',
    icon: '💡',
    emojis: [
      { emoji: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bright'] },
      { emoji: '🔧', name: 'wrench', keywords: ['tool', 'fix', 'repair'] },
      { emoji: '🔨', name: 'hammer', keywords: ['tool', 'build'] },
      { emoji: '⚙️', name: 'gear', keywords: ['settings', 'config'] },
      { emoji: '🔑', name: 'key', keywords: ['key', 'lock', 'password'] },
      { emoji: '🔒', name: 'locked', keywords: ['lock', 'secure', 'private'] },
      { emoji: '🔓', name: 'unlocked', keywords: ['unlock', 'open'] },
      { emoji: '📎', name: 'paperclip', keywords: ['attach', 'clip'] },
      { emoji: '📌', name: 'pushpin', keywords: ['pin', 'location'] },
      { emoji: '📝', name: 'memo', keywords: ['note', 'write', 'memo'] },
      { emoji: '📁', name: 'file folder', keywords: ['folder', 'file'] },
      { emoji: '📂', name: 'open file folder', keywords: ['folder', 'open'] },
      { emoji: '📊', name: 'bar chart', keywords: ['chart', 'stats', 'data'] },
      { emoji: '📈', name: 'chart increasing', keywords: ['growth', 'up', 'profit'] },
      { emoji: '📉', name: 'chart decreasing', keywords: ['down', 'loss'] },
      { emoji: '📧', name: 'e-mail', keywords: ['email', 'mail'] },
      { emoji: '📱', name: 'mobile phone', keywords: ['phone', 'mobile'] },
      { emoji: '💻', name: 'laptop', keywords: ['computer', 'laptop', 'code'] },
      { emoji: '🖥️', name: 'desktop computer', keywords: ['computer', 'desktop'] },
      { emoji: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'] },
      { emoji: '🖱️', name: 'computer mouse', keywords: ['mouse', 'click'] },
      { emoji: '🎮', name: 'video game', keywords: ['game', 'gaming', 'controller'] },
      { emoji: '🎯', name: 'bullseye', keywords: ['target', 'goal', 'dart'] },
      { emoji: '🎲', name: 'game die', keywords: ['dice', 'game', 'random'] },
      { emoji: '🧩', name: 'puzzle piece', keywords: ['puzzle', 'piece'] },
      { emoji: '🎵', name: 'musical note', keywords: ['music', 'note'] },
      { emoji: '🎶', name: 'musical notes', keywords: ['music', 'notes'] },
      { emoji: '🎤', name: 'microphone', keywords: ['mic', 'karaoke', 'sing'] },
      { emoji: '🎧', name: 'headphone', keywords: ['headphones', 'music'] },
      { emoji: '📷', name: 'camera', keywords: ['camera', 'photo'] },
      { emoji: '📸', name: 'camera with flash', keywords: ['camera', 'photo', 'flash'] },
      { emoji: '📹', name: 'video camera', keywords: ['video', 'record'] },
      { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film'] },
      { emoji: '📺', name: 'television', keywords: ['tv', 'watch'] },
      { emoji: '🔔', name: 'bell', keywords: ['bell', 'notification', 'alert'] },
      { emoji: '🔕', name: 'bell with slash', keywords: ['mute', 'silent'] },
      { emoji: '📢', name: 'loudspeaker', keywords: ['announcement', 'loud'] },
      { emoji: '🏷️', name: 'label', keywords: ['tag', 'label'] },
      { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete', 'bin'] },
      { emoji: '📦', name: 'package', keywords: ['box', 'package', 'delivery'] }
    ]
  },
  {
    name: 'symbols',
    label: 'Symbole',
    icon: '✅',
    emojis: [
      { emoji: '✅', name: 'check mark button', keywords: ['check', 'done', 'yes'] },
      { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'error'] },
      { emoji: '❓', name: 'question mark', keywords: ['question', 'what'] },
      { emoji: '❗', name: 'exclamation mark', keywords: ['important', 'warning'] },
      { emoji: '⚠️', name: 'warning', keywords: ['warning', 'caution'] },
      { emoji: '🚫', name: 'prohibited', keywords: ['no', 'forbidden', 'ban'] },
      { emoji: '⛔', name: 'no entry', keywords: ['stop', 'forbidden'] },
      { emoji: '♻️', name: 'recycling symbol', keywords: ['recycle', 'green'] },
      { emoji: '💤', name: 'zzz', keywords: ['sleep', 'tired'] },
      { emoji: '🔄', name: 'counterclockwise arrows', keywords: ['refresh', 'reload', 'sync'] },
      { emoji: '⏰', name: 'alarm clock', keywords: ['clock', 'time', 'alarm'] },
      { emoji: '⏳', name: 'hourglass not done', keywords: ['time', 'wait'] },
      { emoji: '🏁', name: 'chequered flag', keywords: ['finish', 'race', 'done'] },
      { emoji: '🚀', name: 'rocket', keywords: ['rocket', 'launch', 'fast', 'ship'] },
      { emoji: '🎉', name: 'party popper', keywords: ['party', 'celebrate', 'tada'] },
      { emoji: '🎊', name: 'confetti ball', keywords: ['party', 'celebrate'] },
      { emoji: '🏆', name: 'trophy', keywords: ['trophy', 'win', 'champion'] },
      { emoji: '🥇', name: 'gold medal', keywords: ['first', 'winner', 'gold'] },
      { emoji: '🥈', name: 'silver medal', keywords: ['second', 'silver'] },
      { emoji: '🥉', name: 'bronze medal', keywords: ['third', 'bronze'] },
      { emoji: '🎁', name: 'wrapped gift', keywords: ['gift', 'present', 'birthday'] },
      { emoji: '🪄', name: 'magic wand', keywords: ['magic', 'wizard'] },
      { emoji: '📍', name: 'round pushpin', keywords: ['location', 'pin'] },
      { emoji: '🔗', name: 'link', keywords: ['link', 'url', 'chain'] },
      { emoji: '➡️', name: 'right arrow', keywords: ['right', 'next'] },
      { emoji: '⬅️', name: 'left arrow', keywords: ['left', 'back'] },
      { emoji: '⬆️', name: 'up arrow', keywords: ['up'] },
      { emoji: '⬇️', name: 'down arrow', keywords: ['down'] },
      { emoji: '➕', name: 'plus', keywords: ['plus', 'add'] },
      { emoji: '➖', name: 'minus', keywords: ['minus', 'subtract'] },
      { emoji: '💬', name: 'speech balloon', keywords: ['chat', 'message', 'comment'] },
      { emoji: '💭', name: 'thought balloon', keywords: ['think', 'thought'] },
      { emoji: '🗨️', name: 'left speech bubble', keywords: ['chat', 'talk'] },
      { emoji: '👀', name: 'eyes', keywords: ['look', 'see', 'watch'] },
      { emoji: '👁️', name: 'eye', keywords: ['look', 'see'] },
      { emoji: '🧠', name: 'brain', keywords: ['brain', 'smart', 'think'] },
      { emoji: '🫡', name: 'saluting face', keywords: ['salute', 'respect', 'aye'] },
      { emoji: '⚡', name: 'high voltage', keywords: ['lightning', 'fast', 'electric'] },
      { emoji: '☀️', name: 'sun', keywords: ['sun', 'sunny', 'bright'] },
      { emoji: '🌙', name: 'crescent moon', keywords: ['moon', 'night'] }
    ]
  }
]

// Flat array of all emojis for search
export const allEmojis = emojiCategories.flatMap((cat) =>
  cat.emojis.map((e) => ({ ...e, category: cat.name }))
)
